name: Daily Bizinfo Bot

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 google-generativeai


      - name: Run script
        run: python bizinfo_bot.py
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
